insert into Matricula (valor_matricula, beneficiario) values ('123456789', true);
insert into Matricula (valor_matricula, beneficiario) values ('987654321', false);
insert into Matricula (valor_matricula, beneficiario) values ('223436367', true);
insert into Matricula (valor_matricula, beneficiario)values ('373738838', true);
insert into Matricula (valor_matricula, beneficiario) values ('423383989', false);
insert into Matricula (valor_matricula, beneficiario) values ('538339393', true);
insert into Matricula (valor_matricula, beneficiario) values ('683837783', false);
insert into Matricula (valor_matricula, beneficiario) values ('773738388', false);
insert into Matricula (valor_matricula, beneficiario) values ('899202020', false);
insert into Matricula (valor_matricula, beneficiario) values ('923436367', false);
insert into Matricula (valor_matricula, beneficiario) values ('173738838', true);
insert into Matricula (valor_matricula, beneficiario) values ('283383889', false);
insert into Matricula (valor_matricula, beneficiario) values ('338383833', false);
insert into Matricula (valor_matricula, beneficiario) values ('488383838', true);
insert into Matricula (valor_matricula, beneficiario) values ('593939393', false);
insert into Matricula (valor_matricula, beneficiario) values ('683838383', false);
insert into Matricula (valor_matricula, beneficiario) values ('793939399', false);
insert into Matricula (valor_matricula, beneficiario) values ('839399393', true);
insert into Matricula (valor_matricula, beneficiario) values ('998338383', false);
insert into Matricula (valor_matricula, beneficiario) values ('138838383', false);
insert into Matricula (valor_matricula, beneficiario) values ('238333939', false);
insert into Matricula (valor_matricula, beneficiario) values ('393939999', true);
insert into Matricula (valor_matricula, beneficiario) values ('493939333', true);
insert into Matricula (valor_matricula, beneficiario) values ('593939939', true);
insert into Matricula (valor_matricula, beneficiario) values ('118110400', true);
insert into Matricula (valor_matricula, beneficiario) values ('119210030', true);
insert into Matricula (valor_matricula, beneficiario) values ('118210644', true);
insert into Matricula (valor_matricula, beneficiario) values ('118110388', true);
insert into Matricula (valor_matricula, beneficiario) values ('119210094', true);
insert into Matricula (valor_matricula, beneficiario) values ('username', true);
insert into Matricula (valor_matricula, beneficiario) values ('admin', false);

insert into tb_role (authority) values ('ROLE_BENEFICIARIO');
insert into tb_role (authority) values ('ROLE_EXTERNO');
insert into tb_role (authority) values ('ROLE_ADMINISTRADOR');
insert into tb_role (authority) values ('ROLE_NUTRICIONISTA');

insert into usuario(matricula, beneficiario, email, nome, senha, role_authority, telefone, credito, url_imagem) values('username', true, 'usuario@test.com', 'teste', '$2a$10$xSTD2GboaSR20i5xzmX/EOPvT0x7ZywzFuisOUOwU3Hy4YVTDcqUG' , 'ROLE_BENEFICIARIO', '83983834822', 0.0, '');
insert into usuario(matricula, beneficiario, email, nome, senha, role_authority, telefone, credito, url_imagem) values('admin', true, 'admin@test.com', 'teste', '$2a$10$xSTD2GboaSR20i5xzmX/EOPvT0x7ZywzFuisOUOwU3Hy4YVTDcqUG' , 'ROLE_ADMINISTRADOR', '83983834822', 0.0, '');
